# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install openjdk-21-jdk
    java -version
  displayName: 'Install JDK 21'

- task: Maven@4
  inputs:
    azureSubscription: 'Pay-As-You-Go(50d2f6c5-dae3-40fc-98da-10137a9e2d97)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'jarfile'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(50d2f6c5-dae3-40fc-98da-10137a9e2d97)'
    appType: 'webApp'
    WebAppName: 'java-akshay-basic-webapp'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/jarfile/*.jar'